import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';
import { getSession } from '@/lib/auth/session';

export const runtime = 'nodejs';

const EXT_TO_MIME: Record<string, string> = {
  png: 'image/png',
  svg: 'image/svg+xml',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  webp: 'image/webp',
};

// Only allow filenames that match the pattern generated by upload-logo:
// <timestamp>-<hex>.{png|jpg|jpeg|svg|webp}
// Rejects path traversal segments (e.g. ".."), hidden files, or unexpected layouts.
const SAFE_SEGMENT = /^[\w.-]+$/;

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ path: string[] }> },
) {
  // Require a valid session — logos are app-internal assets, not public.
  const session = await getSession();
  if (!session) {
    return new NextResponse(null, { status: 401 });
  }

  const { path } = await params;

  // Guard against path traversal: reject any segment that contains '..'
  // or does not match the safe character set for storage object names.
  for (const segment of path) {
    if (!SAFE_SEGMENT.test(segment) || segment === '..' || segment === '.') {
      return new NextResponse(null, { status: 400 });
    }
  }

  // The path must resolve strictly inside the company-logos/ prefix.
  // Joining safe segments (no '..') cannot escape the prefix.
  const storagePath = `company-logos/${path.join('/')}`;

  const supabase = createServiceClient();
  const { data, error } = await supabase.storage
    .from('worker-files')
    .download(storagePath);

  if (error || !data) {
    return new NextResponse(null, { status: 404 });
  }

  const buffer = await data.arrayBuffer();
  const ext = storagePath.split('.').pop()?.toLowerCase() ?? 'jpg';
  const contentType = EXT_TO_MIME[ext] ?? 'image/jpeg';

  // SVG files served inline with Content-Type: image/svg+xml can execute embedded
  // scripts as XSS on this origin.  New SVG uploads are blocked in upload-logo.
  // For any legacy SVG already in storage, force a download instead of inline render.
  const headers: Record<string, string> = {
    'Content-Type': contentType,
    'Cache-Control': 'private, max-age=3600',
  };
  if (ext === 'svg') {
    headers['Content-Disposition'] = 'attachment; filename="logo.svg"';
  }

  return new NextResponse(buffer, { headers });
}
